### PR TITLE
fix missing imports for ghc 8.6.4

### PR DESCRIPTION
**Pull request by shapr**
With ghc 8.6.4 hoauth2 would not build on my laptop due to missing imports.
This is a quick fix to get it building for me.
I hope this is useful, I did not dig in to see if there's a different root problem!

### CODE REVIEW

**Comment by freizl** [comment]
Probably because aeson changes between 1.3.x and 1.4.x?
Did you try to upgrade stack LTS https://github.com/freizl/hoauth2/blob/master/stack.yaml ?

**Comment by freizl** [comment]
hmm,
I dont see why we need
```
import           Data.Aeson.Types (allNullaryToStringTag, camelTo2,
                                   constructorTagModifier)
```

which are all exposed via `Data.Aeson`. Would like to dig a little bit more?

**Comment by shapr** [comment]
Hello,
I don't use stack. I made these changes because I was unable to build hoauth2 with "cabal new-build" with cabal 2.4.1.0

otherwise I get this result:

```
Resolving dependencies...
    Perhaps you want to add ‘constructorTagModifier’ to the import list
    in the import of ‘Data.Aeson.Types’
    (src/Network/OAuth/OAuth2/Internal.hs:17:1-67).
   |
96 |   toJSON = genericToJSON defaultOptions { constructorTagModifier = camelTo2 '_', allNullaryToStringTag = True }
   |                                           ^^^^^^^^^^^^^^^^^^^^^^

src/Network/OAuth/OAuth2/Internal.hs:96:82: error:
    Not in scope: ‘allNullaryToStringTag’
    Perhaps you want to add ‘allNullaryToStringTag’ to the import list
    in the import of ‘Data.Aeson.Types’
    (src/Network/OAuth/OAuth2/Internal.hs:17:1-67).
   |
96 |   toJSON = genericToJSON defaultOptions { constructorTagModifier = camelTo2 '_', allNullaryToStringTag = True }
   |                                                                                  ^^^^^^^^^^^^^^^^^^^^^

src/Network/OAuth/OAuth2/Internal.hs:97:51: error:
    Not in scope: ‘constructorTagModifier’
    Perhaps you want to add ‘constructorTagModifier’ to the import list
    in the import of ‘Data.Aeson.Types’
    (src/Network/OAuth/OAuth2/Internal.hs:17:1-67).
   |
97 |   toEncoding = genericToEncoding defaultOptions { constructorTagModifier = camelTo2 '_', allNullaryToStringTag = True }
   |                                                   ^^^^^^^^^^^^^^^^^^^^^^

src/Network/OAuth/OAuth2/Internal.hs:97:90: error:
    Not in scope: ‘allNullaryToStringTag’
    Perhaps you want to add ‘allNullaryToStringTag’ to the import list
    in the import of ‘Data.Aeson.Types’
    (src/Network/OAuth/OAuth2/Internal.hs:17:1-67).
   |
97 |   toEncoding = genericToEncoding defaultOptions { constructorTagModifier = camelTo2 '_', allNullaryToStringTag = True }
   |                                                                                          ^^^^^^^^^^^^^^^^^^^^^
[3 of 5] Compiling Network.OAuth.OAuth2.TokenRequest ( src/Network/OAuth/OAuth2/TokenRequest.hs, dist/build/Network/OAuth/OAuth2/TokenRequest.o )

src/Network/OAuth/OAuth2/TokenRequest.hs:9:49: error:
    Not in scope: ‘constructorTagModifier’
  |
9 |   parseJSON = genericParseJSON defaultOptions { constructorTagModifier = camelTo2 '_', allNullaryToStringTag = True }
  |                                                 ^^^^^^^^^^^^^^^^^^^^^^

src/Network/OAuth/OAuth2/TokenRequest.hs:9:88: error:
    Not in scope: ‘allNullaryToStringTag’
  |
9 |   parseJSON = genericParseJSON defaultOptions { constructorTagModifier = camelTo2 '_', allNullaryToStringTag = True }
  |                                                                                        ^^^^^^^^^^^^^^^^^^^^^

src/Network/OAuth/OAuth2/TokenRequest.hs:11:51: error:
    Not in scope: ‘constructorTagModifier’
   |
11 |   toEncoding = genericToEncoding defaultOptions { constructorTagModifier = camelTo2 '_', allNullaryToStringTag = True }
   |                                                   ^^^^^^^^^^^^^^^^^^^^^^

src/Network/OAuth/OAuth2/TokenRequest.hs:11:90: error:
    Not in scope: ‘allNullaryToStringTag’
   |
11 |   toEncoding = genericToEncoding defaultOptions { constructorTagModifier = camelTo2 '_', allNullaryToStringTag = True }
   |       
```

**Comment by freizl** [comment]
@shapr I think it's because it's downloading an old version of `aeson`. I fixed at https://github.com/freizl/hoauth2/commit/bc79ef7ab4b9d785ad0a412bef7eb22b1a9b2177 and release `1.8.8`.
Let me know if it works for you. Thank you for reporting issue!

**Comment by freizl** [comment]
shall be fix now.

**Pull request closed without merging**
